### ISSUE TITLE
Punctuation mark breaks to new line

### ISSUE THREAD

**Issue by WebSnke** [jdm-contrib/jdm#1583]
The dot at the end of the Chrome/Firefox extension section is breaking.
white-space: nowrap; resolves the issue but this would break the mobile version.

Screenshot:
![image](https://user-images.githubusercontent.com/94064167/230588570-f0014db5-3dfe-4d79-aa56-615f4a472c8b.png)

**Comment by MattiaRaffaele** [comment]
Maybe we should remove the dot I dont think it would make a big difference

**Comment by Nightfirecat** [comment]
The reason for the break is because there is a space in the source between the link and the period:

![Screenshot_20230628_210336](https://github.com/jdm-contrib/jdm/assets/2199511/795b5c18-eae9-4738-b218-da6ea09da7ef)

The reason for that space is because `extensionp5` is a piece of translation text which is used when some trailing text is needed for certain languages, such as "auf" in German. We could get around this by moving that optional space into the translation text and removing it from the source, and I intend to raise a PR to do just that. Once removed, that text in English appears on a single line as expected.
