### ISSUE TITLE
The Chrome extension page linked from the site is a 404 page

### ISSUE THREAD

**Issue by ldexterldesign** [jdm-contrib/jdm#1772]
👋

As title

Screenshot:
<img width="1840" alt="Screenshot 2023-09-12 at 18 43 48" src="https://github.com/jdm-contrib/jdm/assets/1715809/53cb806e-3287-45bc-a995-6f0272418615">

# Steps to reproduce issue

Go to [Chrome extension page]

# Unexpected behaviour

Dead page

# Expected behaviour

Live page

If you're reading and:
* agree then please vote up (e.g. +1, like), or;
* disagree then please vote down (e.g. -1, dislike) - I'd love to know why?

Hope this helps

Regards

[Chrome extension page]: https://chrome.google.com/webstore/detail/justdeleteme/hfpofkfbabpbbmchmiekfnlcgaedbgcf

**Comment by Nightfirecat** [comment]
Per https://github.com/jdm-contrib/justdelete.me-chrome-extension, the Chrome extension is no longer maintained. I can't say I recall offhand why that is--whether there were technical changes which we don't have bandwidth to support, or for other reasons.

**Comment by ldexterldesign** [comment]
Thanks for reply

Oh, that's a shame

I see last repo' commit was in 2018 - I'm only 5 years late to notice!

Regards

**Comment by tupaschoal** [comment]
I think it was a combined lack of interest from the community and lack of time from us maintainers

**Comment by Nightfirecat** [comment]
I'm gonna re-open this issue, as we shouldn't be linking to a dead Chrome web store link on the site.

**Comment by Abdelmalek-HAMZA** [comment]
I created a mobile application for the android platform that uses the links in **_data/sites.json**, and I wanna be part of the community and make it as the official app for this open source project, please do not hesitate to check it at [Google Play Store](https://play.google.com/store/apps/details?id=com.dhad.delete.me&pcampaignid=web_share)

All your feedback is welcome.

**Comment by ldexterldesign** [comment]
If the effort is minimal then seems a shame not to have code browser parity 🤷

**Comment by tupaschoal** [comment]
> Judging by [the code](https://github.com/jdm-contrib/justdelete.me-chrome-extension/blob/c7ec415f20b3b67812e85f9ed9b1af9f57c5373b/js/background.js), I can probably rewrite a modern version of it and publish it in an hour, if there's any interest in keeping an official link to it.

I'd happily take a PR to bring it to modern era

**Comment by fregante** [comment]
More than a PR, I was thinking of a new extension/repo that I can maintain personally. I'm not particularly into rewriting projects and then hoping that they won't end up unmaintained again (happened several times before) 😅 especially because, like in this case, the web store requires direct access and changes.

**Comment by PyroSamurai** [comment]
@fregante Shouldn't be an issue to do it your way, we'll just put your repo into the organization when it's ready.
You'll still have full ownership over the repo.

**Comment by fregante** [comment]
I submitted a version to the CWS, I'll let you know when they approve it ☺️ 

The extension has "no permissions" and only runs javascript once a day. The update of the toolbar icon is handled by the browser itself, without custom listeners, via [declarativeContent](https://developer.chrome.com/docs/extensions/reference/declarativeContent/). The API is a bit limited but it serves its basic purpose. 

I opted to point the user to `JustDeleteMe.xyz/#current.site.com` on click so that further instructions can be followed there. There's an issue with the filtering there though, because these two searches are empty:

- https://justdeleteme.xyz/#www.youtube.com
- https://justdeleteme.xyz/#youtube.com

while this works:

- https://justdeleteme.xyz/#youtube

It'd be great to use the `domains` array on the website’s search as well in order to find them easily, not just by name.

**Comment by fregante** [comment]
![gif](https://github.com/jdm-contrib/jdm/assets/1402241/32b7761f-26ca-4913-8686-b76b8c0ea0a3)

**Comment by tupaschoal** [comment]
> @fregante Shouldn't be an issue to do it your way, we'll just put your repo into the organization when it's ready.
> You'll still have full ownership over the repo.

Yes! I mentioned a PR because we could reuse the repo that already exists, but you could have one commit deleting everything and another adding your version of the extension

**Comment by fregante** [comment]
The extension has been available on the store for 2 days, I didn't even notice 😅 

Store: https://chrome.google.com/webstore/detail/just-delete-me/dlhckcablohllindinahbbpnfgblimoe
Source: https://github.com/fregante/jdm

No permissions required:

<img width="732" alt="Screenshot" src="https://github.com/jdm-contrib/jdm/assets/1402241/f754c6e1-015d-4b16-a57f-c44fe0aa0d22">

**Comment by ldexterldesign** [comment]
@fregante 👏😘

**Comment by fregante** [comment]
> The Chrome extension page linked from the site is a 404 page

Still is
