### ISSUE TITLE
About web design

### ISSUE THREAD

**Issue by GrimPixel** [jdm-contrib/jdm#282]
I think “What is this?” and “Guide” divisions should be placed on the top. After viewing a bit of the page, there would be no need to see them, especially “Guide”. Also for that extension.

**Comment by GrimPixel** [comment]
In addition, those words “easy”, “medium”, “hard”, “impossible” seems to be valuable only to color-blind people. If you want to give color-blind people a consideration, you can place them on the right-most of the website name bar with their initial letters. This can make the website more compact.

**Comment by PyroSamurai** [comment]
I've thought about it from time to time. Probably something like an accordion drop-down area for them  below or above the search input, but I don't really have too much time to think about the site and it works well as-is. So I'm not-committal lol

**Comment by Nightfirecat** [comment]
Honestly, I'm kind of confused about this suggestion. The "About" section which contains both the "What is this?" and "Guide" sections is at the bottom of the page, so even if you are familiar with the site, you would not encounter it unless you were looking for it.

As for the suggestion on the difficulty word placement, I'm assuming you mean they could be placed differently on the cards themselves? I feel that could be done, though we'd want to be mindful of simply moving that text into the card title bars since we have a limited amount of space to work with there.

**Comment by tupaschoal** [comment]
I'm closing this issue as we didn't converge.
