### ISSUE TITLE
[Discussion] Differenting between deletion and closing an account.

### ISSUE THREAD

**Issue by jtagcat** [jdm-contrib/jdm#578]
By our current definitions, closing an account means that it's impossible to close.

I would propose, that we have easy-hard-impossible and a sepearte 'will it actually delete, or just close', as:
 - Instead of closing the account, the user might just walk away, potentially leaving their information public (instead of private, shared with the company)
 - You can't show, is it an easy-to-close or hard-to-close, while with deletion you can-

**Comment by tupaschoal** [comment]
Hmm, I've been thinking about this and I'm not sure I fully agree. The idea of the website is to state how you can delete your account. Closing is not deleting, so for me it is `impossible`. 

I think so far we have done our best to explain in the notes that closing is possible and sometimes easy, but that it doesn't delete the data. I like that we are rigid and make it look bad to those services because what we want is actually to push for ease and transparency in the deletion process.

Thoughts @PyroSamurai and @Nightfirecat ?

**Comment by PyroSamurai** [comment]
I'm of the same opinion as you @tupaschoal .

**Comment by jtagcat** [comment]
What about adding `impossible¹` or `impossible*` for non-deletable closing (and make the ?

I think we agree that closing an account is better than impossible (should be done). If the user sees `impossible`:

![image](https://user-images.githubusercontent.com/38327267/87083543-51795380-c21c-11ea-9e91-658144020f61.png)

it might lead to 'k, nothing can be done, ctrl+w'.

If there is at least one `impossible*` present, show the remark:
![image](https://user-images.githubusercontent.com/38327267/87084080-29d6bb00-c21d-11ea-827f-01129cfef327.png)

..but in the default view (showing everything), they would be present (clutters the view).

One options is tooltips, add a wavy underline with an icon![info icon](https://design.firefox.com/icons/icons/android/info-24.svg) (that could be done with all difficulties, eliminating or decreasing the need for [the guide](https://justdeleteme.xyz/#about)).

In the filters, `impossible` and `impossible*` should be the same thing. I guess the tooltips are our best option. Any other ideas?

**Comment by tupaschoal** [comment]
> it might lead to 'k, nothing can be done, ctrl+w'.

I agree that this might be one of the possible outcomes, but the "show info" is there for a reason and by reading it, the user might get the same information that they would get with a `1` superscript, tooltip or similar. After all, they might just see the impossible and never hover too, right?

And to add the superscript we would still have to add an extra field to the JSON, which is not something I'm really fond of because it's really impossible, after all :(

**Comment by jtagcat** [comment]
I guess there's nothing else to be said then.
