### ISSUE TITLE
Problematic usage of flags for languages

### ISSUE THREAD

**Issue by toastal** [jdm-contrib/jdm#972]
[Flags represent nations, not languages](http://www.flagsarenotlanguages.com/). Please use the [‘turnstyle’ language icon](http://www.languageicon.org/) if an icon is necessary and use the language name and/or language code to signify the language.

Some obviously controversial flags: [United Kingdom](https://en.wikipedia.org/wiki/Geographical_distribution_of_English_speakers), [Spain](https://en.wikipedia.org/wiki/Hispanophone), [France](https://en.wikipedia.org/wiki/Geographical_distribution_of_French_speakers), [Portugal](https://en.wikipedia.org/wiki/Geographical_distribution_of_Portuguese_speakers) (though this project uses Brazil (which is consistent with what exactly?)). These examples have more speakers outside the origin country than within and is a very Euro-centric, colonial viewpoint of language to use any flag whatsoever.

Not to mention, many countries have more than one language which further propagates stereotypes or belittlement of minority groups inside those countries.

---

Related: #940, #943

**Comment by Foggalong** [comment]
Just to flag (no pun intended), that turnstyle icon is licensed really weirdly. It says that it's Creative Commons but doesn't specify which CC license and has a bunch of very specific and ambiguous conditions that aren't CC friendly (whether reshaping the icon is permitted is ambiguous for example). Wouldn't be comfortable using something licensed that ambiguously in any project, much less an MIT licensed one, so going to look around for an alternative which has clearer licensing.

**Comment by Foggalong** [comment]
Doing a search around this is a known problem with this icon, even mentioned on [its Wiki page](https://en.wikipedia.org/wiki/Language_Icon). Font Awesome had similar concerns I assume because between versions 4 and 5 they switched [from using it](https://github.com/Rush/Font-Awesome-SVG-PNG/blob/master/black/svg/language.svg) to [their own solution](https://fontawesome.com/v5.15/icons/language?style=solid); the latter is simply CC-BY 4.0 licensed so can tweak that and get it included no problem :+1:

**Comment by toastal** [comment]
> Can I use the Language Icon Freely?
>
> *Yes*, you can use the Language Icon for commercial and non-commercial projects; A' Design Award & Competition, who has organized the Language Icon design competition, Farhat Datta, the creator of the new Language Icon, and Onur Mustak Cobanli, the creator of the original idea hereby declare that the Language Icon is a collaborated creation released with a CC license with following terms: *Relax-Attribution.* You are suggested but not required to attribute the work when using for internet / digital use. You must attribute it in any other use which is not on internet. Attribute to: A’ Design Award & Competition, Onur Müştak Çobanlı and Farhat Datta with URL http://www.languageicon.org for non-internet usage.  *Share Alike.* If you alter, transform, or build upon this work, you may distribute the resulting work only under the same or similar license to this one, attribute to original author, resulting work cannot be commercial. *Semi-Noncommercial.* You may not use this work as a central element (or one of the core elements) for commercial purposes; Such as a design on a tshirt, on a book cover etc unless you attribute to the author. On the other hand you can use freely in your websites without attribution to signify language. *Color-Firendly*: You can change the colors as you like, keep the form intact please; scale proportionally. You can reverse the color or grayscale it if required.

I hadn't seen the controversy and just read about it. Given these are the stipulations, what's objectionable? That it's a non-stardard, CC-like-but-not-CC license? I can see and have seen issues around all forms of "noncommercial" but in its "intended" purpose, like in a language switcher, I wouldn't see a specific issue with since it'd be hard to argue that a such a UI widget is "a central element".

CC issue with suggestions: https://github.com/creativecommons/creativecommons.org/issues/1194

**Comment by toastal** [comment]
Not opposed to the Font Awesome one though there was a throught-provoking comment in the CC thread

> A Korean acquaintance of mine also criticised the OP icon as seemingly equating ㅊ and A, despite no phonological overlap. あ and A make more sense as there is such overlap.

liking a CC0 suggestion like https://www.clipsafari.com/clips/o213245-translation-icon

**Comment by Foggalong** [comment]
> Given these are the stipulations, what's objectionable? That it's a non-stardard?

Pretty much, if a project is claiming to be open source or free software/art but is using a non-standard or hodgepodge license it's a bit of a red flag. It doesn't necessarily mean the project or even the license is bad, but it's usually a good indicator that it won't thoroughly have been checked over for errors, contradictions, etc.

Specifically with Language Icon, the "Color-Firendly" term in its license stipulates

> _change the colors as you like, keep the form intact please; scale proportionally._

This is in conflict with the implication in the share alike term that alterations and transformations are allowed. I'll be making some slight modifications to optimize it for the display size.

> there was a throught-provoking comment in the CC thread

My understanding based on looking through the git logs is that the character in Font Awesome is 文 from Chinese rather than ㅊ from Korean (unlike [WikiMedia](https://commons.wikimedia.org/wiki/File:Icon_-_Foreign_characters_gray.svg)). I don't know enough about either language as to speak to its appropriateness, but it does mean Font Awesome is using the same characters as [the icon](https://fonts.google.com/icons?selected=Material+Icons:translate) the CC thread landed on.
